### ISSUE TITLE
Allow to select variables before plotting

### ISSUE THREAD

**Issue by CSchoel** [THM-MoTE/webmodelica#109]
Usually a Modelica model has many more variables than what is actually interesting. It would conserve a lot of resources, if the user was able (but not forced) to select plotting variables before simulation.

**Comment by njustus** [comment]
I've added a rudimentary selection that uses a simple text field for the variable names.

![Screenshot from 2019-08-10 18-11-42](https://user-images.githubusercontent.com/9325639/62824153-5a8c1b80-bb9a-11e9-91b4-879f520fb04f.png)
