### ISSUE TITLE
New file is created always with declaration model

### ISSUE THREAD

**Issue by andreasdominik** [THM-MoTE/webmodelica#131]
Every new file is created as "model ...".
If something else is selected in the dropdown this should be adopted in the file (such as "connector ..." if new connector have been selected).

**Comment by cifland** [comment]
I couldn't reproduce this behaviour, it works on my device.

**Comment by cifland** [comment]
Found the problem and fixed it. Turns out firefox works with html statements that chrome doesn't accept.
