### ISSUE TITLE
Better overview for large projects

### ISSUE THREAD

**Issue by CSchoel** [THM-MoTE/webmodelica#65]
I just loaded my thesis project in webmodelica with 219 files. It was possible but a lot of scrolling was involved. :wink: 

Although the focus of webmodelica should be on small example projects, I think having a better overview (tree view?) of files in a project is still desirable.

**Comment by njustus** [comment]
I'm suprised that in fact you *can load* 219 files :laughing: ..

Sure a better tree view would be good :+1: .

**Comment by njustus** [comment]
How about this?

![Screenshot from 2019-05-23 11-42-25](https://user-images.githubusercontent.com/9325639/58244938-eccb1300-7d53-11e9-8710-83c31816c8d1.png)

**Comment by njustus** [comment]
Soo finally there is a file tree and its deployed onto *staging-webmodelica* . As before: please kill browser's cache and cookies.
Its now possible to log in via GitHub or the developer login.. If you like to use the already existing account: just input your username in the dev login.

The tree is a little buggy and looses the collapsing state quite often. Going to fix it later.
